name: assembly_pipeline

channels:
  - bioconda
  - conda-forge
  - r

dependencies:
        
  - bioconda::snakemake-minimal =5.13.0
  - python =3.7
  - singularity =3.5.2
  - graphviz =2.38.0
  - squashfs-tools =4.3
  - jellyfish =2.2.10
  - r =3.6.0
  - r-pryr =0.1.4
    #- r-pracma =1.8.8
