name: assembly_pipeline

channels:
  - bioconda
  - conda-forge
  

dependencies:
        
  - bioconda::snakemake-minimal =5.13.0
  - python =3.8
  - singularity =3.5.2
  - graphviz =2.38.0
  - squashfs-tools =4.3
